config/routes.rb
Spyrolous::Application.routes.draw do

  root "pages#index"

  # need to clean up these routes to be more specific since I'm not writing all of the standard methods in the controllers

  resources :canvases do
    resources :layers do 
      resources :circles
      resources :rectangles
      resources :paths
      resources :spyros
    end
  end

  # resources :artists

  get "/dashboard" => "artists#show"

  # route for live streaming the canvas to multiple users
  get "/canvases/:canvas_id/layers/:id/stream" => "layers#stream"

  # for omniauth callbacks
  get 'auth/:provider/callback' => "artists#login"

  #logout the user
  get '/logout' => 'artists#logout'

  # get pre-processes svgs of canvases
  get '/canvases/svgs/:id/' => 'canvas_svgs#show'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_and_belongs_to_many :canvases
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def login
    artist = Artist.find_or_create_by(google_id: auth_hash['uid'])
    artist.update_attributes(artist_attributes)
    # if artist exists, log them in
    if artist
      session[:artist_id] = artist.id
      redirect_to '/dashboard'
    else
      redirect_to root_url
    end
  end

  def logout
    session[:artist_id] = nil
    redirect_to root_url
  end


  def show
    if current_user
      @artist = current_user
    else 
      redirect_to root_url
    end
    # need to show the canvases associated with each user here
    # render canvases#index as partial?
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def artist_attributes
    {
      name: request.env['omniauth.auth']['info']['name'],
      image: request.env['omniauth.auth']['info']['image']
    }
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/new.html.haml
= @user.data

app/views/artists/show.html.haml
.pure-g-r
  .pure-u-1-5
    =link_to "new canvas", new_canvas_path, {class:"pure-button", id:"newCanvas"}
  .pure-u-3-5.canvasIndex
    %h3 My Canvases
    -@artist.canvases.each do |c|
      %a{href:"/canvases/#{c.id}"}
        .canvasThumb{id:"c#{c.id}"}
          :javascript
            var s#{c.id} = Snap("#c#{c.id}");
            Snap.load("/canvases/svgs/#{c.id}.svg", function(f){
            s#{c.id}.append(f);
            });
  .pure-u-1-5     